### ISSUE TITLE
Graphs show no data

### ISSUE THREAD

**Issue by utsengar** [nkrode/RedisLive#48]
I am running a redis live instance on the same machine where redis is running. I am able to see the stats but I don't see any graphs. Also, triggered redis-monitor.py which is setup as an hourly cron.

Screenshot: http://s24.postimg.org/6ux9mm98k/Screenshot_from_2013_04_03_17_10_06.jpg

Any suggestions about what is going on?

redis-live.conf

```
{
        "RedisServers":
        [
                {
                  "server": "127.0.0.1",
                  "port" : 8080
                }
        ],

        "DataStoreType" : "sqlite",

        "RedisStatsServer":
        {
                "server" : "127.0.0.1",
                "port" : 6381
        }
}
```

Thanks,
-Utkarsh

**Comment by raingolee** [comment]
anyone have fix this bug? could u guys help me?
