### ISSUE TITLE
got "no such table: monitor" when i view page url with config "DataStoreType" as "sqlite"

### ISSUE THREAD

**Issue by five3** [nkrode/RedisLive#60]
i config the "DataStoreType" as  "sqlite", and got "no such table: monitor" error when view the page url.

redis-live.conf:
	"DataStoreType" : "sqlite", 
	
	"SqliteStatsStore" :
	{
		"path":  "D:/performance/api.product/redisCache/redis.sqlite"
	}

error info:
    Traceback (most recent call last):
      File "C:\Python27\lib\site-packages\tornado\web.py", line 1141, in _when_c
omplete
        callback()
      File "C:\Python27\lib\site-packages\tornado\web.py", line 1162, in _execut
e_method
        self._when_complete(method(*self.path_args, **self.path_kwargs),
      File "D:\Program Files\RedisLive\src\api\controller\TopKeysController.py",
 line 25, in get
        for data in self.stats_provider.get_top_keys_stats(server, start, end):
      File "D:\Program Files\RedisLive\src\dataprovider\sqliteprovider.py", line
 178, in get_top_keys_stats
        return [[r[0], r[1]] for r in c.execute(query, values)]
    OperationalError: no such table: monitor
[E 131223 11:53:32 web:1635] 500 GET /api/topkeys?from=&to=&server=10.255.254.29
%3A6379 (127.0.0.1) 0.00ms

is there need to init the sqlite db first? thanks!

**Comment by nkrode** [comment]
The tables need to be created. The init scripts as used by @sp2hari should do the trick or as mentioned by @leto the default sqlite file provided has the DB schema initialized.
