### ISSUE TITLE
my monitor machine can't access the   the js from google, so  how can I use redis-live

### ISSUE THREAD

**Issue by xiaochongchong86** [nkrode/RedisLive#69]
my monitor just have a private ip, can't surffing the  internate , which js file show i down load from google, could you tell me ?  tks

**Comment by nkrode** [comment]
Google Chart API is used as an external js file. Not sure what the workaround is for China blocking Google. Maybe try the suggestion from @no13bus

**Comment by yuruli2058** [comment]
https://github.com/LittlePeng/redis-monitor
