### ISSUE TITLE
No realtime data

### ISSUE THREAD

**Issue by jaggerwang** [nkrode/RedisLive#72]
I can see last 15 min, last 1 hour, etc. But realtime data is always empty, the monitor crontab item set as follows。
*/5 * * * * cd ~/RedisLive/src && ./redis-monitor.py --duration=60 >>~/tmp/cron.log 2>&1

![image](https://cloud.githubusercontent.com/assets/1255011/5557078/9e199230-8d2b-11e4-90c4-03c551b26a40.png)
![image](https://cloud.githubusercontent.com/assets/1255011/5557080/ad192aca-8d2b-11e4-945d-3670af3ddeef.png)

**Comment by nkrode** [comment]
#71 is merged
